version: '3.7'
services:
  mysql:
    image: mysql:8.0.28
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data_mysql:/var/lib/mysql
      - ./db_scheme:/docker-entrypoint-initdb.d
